#!/usr/bin/env ruby

cmds = [
  "echo y | gem uninstall rubot",
  "gem build rubot.gemspec",
  "gem install rubot"
]

# clean all old gem files

Dir["*.gem"].each {|file| File.delete file}

cmds.each do |cmd|
  IO.popen(cmd) do |process|
    process.each {|line| puts line}
  end
end
